todoapp/__init__.py
from flask import Flask
from .main.routes import main
from .extensions import mongo
def create_app():
    app = Flask(__name__)
    app.config['MONGO_URI'] = 'mongodb+srv://admin:Password1@cluster0.da5k8.mongodb.net/mydb?retryWrites=true&w=majority'
    mongo.init_app(app)
    app.register_blueprint(main)
    return app

todoapp/main/routes.py
from flask import Blueprint, render_template, redirect, url_for, request
from bson.objectid import ObjectId
from todoapp.extensions import mongo
# from .extensions import mongo
main = Blueprint('main',__name__)

@main.route('/')
def index():
    # saved_todos = todos.find()
    todos_collection = mongo.db.todos
    todos = todos_collection.find()
    return render_template('index.html', todos = todos)

@main.route('/add_todo', methods = ['POST'])
def add_todo():
    todos_collection = mongo.db.todos
    todo_item = request.form.get('add-todo')
    #print(todo_item)
    todos_collection.insert_one({'text' : todo_item, 'complete' : False})
    return redirect(url_for('main.index'))

@main.route('/complete_todo/<oid>')
def complete_todo(oid):
    todos_collection = mongo.db.todos
    todo_item = todos_collection.find_one({'_id':ObjectId(oid)})
    todo_item['complete'] = True
    # todos_collection.replace_one({'complete' :False},{'complete' : True})
    return redirect(url_for('main.index'))

@main.route('/delete_completed')
def delete_completed():
    todos_collection = mongo.db.todos
    todos_collection.delete_many({'complete' : True})
    return redirect(url_for('main.index'))

@main.route('/delete_all')
def delete_all():
    todos_collection = mongo.db.todos
    todos_collection.delete_many({})
    return redirect(url_for('main.index'))

todoapp/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ToDo App</title>

    <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='flatly.min.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
</head>

<body>

    <div class="container-fluid" id="wrapper">

        <div class="row">
            <div class="col-lg-4 col-lg-offset-4" id="content">
                <h2>TASKS</h2>

                <form action="{{ url_for('main.add_todo') }}" method="POST" role="form">

                    <div class="form-group">
                        <div class="input-group">
                            <input name="add-todo" type="text" class="form-control"
                                placeholder="Enter todo e.g. Delete junk files" aria-label="Todo"
                                aria-describedby="add-btn">
                            <span class="input-group-btn">
                                <button type="submit" class="btn btn-default" id="add-btn">ADD</button>
                            </span>
                        </div>
                    </div>
                </form>

                <div class="row t10">
                    <div class="col-lg-12">
                        <div class="btn-toolbar">
                            <div class="btn-group">
                                <a type="button" href="{{ url_for('main.delete_completed') }}" class="btn btn-warning">
                                    DELETE COMPLETED
                                </a>
                            </div>
                            <div class="btn-group">
                                <a type="button" href="{{ url_for('main.delete_all') }}" class="btn btn-warning">
                                    DELETE ALL
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

                <ul class="list-group t20">
                    {% for todo in todos %}
                    <a href="{{ url_for('main.complete_todo', oid=todo._id )}}">
                        <li class="list-group-item {% if todo.complete %}todo-completed{% endif %}">
                            {{ todo.text }}
                        </li>
                    </a>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <footer>
            <div class="row pad">
                <div class="col-lg-12 text-center">
                    <!-- Copyright &copy; 2020 <strong>ToDo App</strong> -->
                </div>
            </div>
        </footer>
    </div>
</body>

</html>